on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 */2 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get deps
      run: |
          go get -v -t -d ./...

    - name: Write README.md
      run: |
          go run gen/main.go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit files
      run: |
        git config --local user.email "bot@rob.sh"
        git config --local user.name "github-actions[bot]"
        git add .
        DATE=`date +%s` git commit -m "Update ${DATE}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
